### ISSUE TITLE
Dynamic removal of value in multi-value boxes

### ISSUE THREAD

**Issue by levigeorge1617** [todc/todc-select2#17]
Is there a way to dynamically remove an item from the selection box of a multi-value box programmatic ally?

**Comment by todc** [comment]
Hi @levigeorge1617,

Since this project is really just a CSS skin for [select2](https://select2.github.io/), you might try asking your question there instead.

Out of curiosity, I did some googling and it looks like there isn't an official API to accomplish this. There is a fairly active [issue](https://github.com/select2/select2/issues/2830) where people have been requesting this feature. It includes a few hacks people have developed to get it working.

Hope that helps.
